<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>c++ primer笔记17: exception | 周子江</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="1. Exception HandlingException handling relies on the problem-detecting part throwing an object to a handler. The type and contents of that object allow the two parts to communicate about what went wr">
<meta property="og:type" content="article">
<meta property="og:title" content="c++ primer笔记17: exception">
<meta property="og:url" content="https://zhouzijiang.github.io/2016/03/18/c-primer笔记17-exception/index.html">
<meta property="og:site_name" content="周子江">
<meta property="og:description" content="1. Exception HandlingException handling relies on the problem-detecting part throwing an object to a handler. The type and contents of that object allow the two parts to communicate about what went wr">
<meta property="og:updated_time" content="2016-03-18T10:57:12.729Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="c++ primer笔记17: exception">
<meta name="twitter:description" content="1. Exception HandlingException handling relies on the problem-detecting part throwing an object to a handler. The type and contents of that object allow the two parts to communicate about what went wr">
  
    <link rel="alternative" href="/atom.xml" title="周子江" type="application/atom+xml">
  
  
    <link rel="icon" href="/favicon.png">
  
  <link href="//fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="/css/style.css" type="text/css">
  

</head>
<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">周子江</a>
      </h1>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/">Home</a>
        
          <a class="main-nav-link" href="/archives">Archives</a>
        
      </nav>
      <nav id="sub-nav">
        
          <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="RSS Feed"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="Search"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" results="0" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="https://zhouzijiang.github.io"></form>
      </div>
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-c-primer笔记17-exception" class="article article-type-post" itemscope itemprop="blogPost">
  <div class="article-meta">
    <a href="/2016/03/18/c-primer笔记17-exception/" class="article-date">
  <time datetime="2016-03-18T08:12:04.000Z" itemprop="datePublished">2016-03-18</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      c++ primer笔记17: exception
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <h2 id="1-_Exception_Handling">1. Exception Handling</h2><p>Exception handling relies on the problem-detecting part throwing an object to a handler. The type and contents of that object allow the two parts to communicate about what went wrong.<br><figure class="highlight cpp"><table><tr><td class="code"><pre><span class="line">Sales_item <span class="keyword">operator</span>+(<span class="keyword">const</span> Sales_item&amp; lhs, <span class="keyword">const</span> Sales_item&amp; rhs)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (!lhs.same_isbn(rhs))</span><br><span class="line">        <span class="keyword">throw</span> runtime_error(<span class="string">"Data must refer to same ISBN"</span>);</span><br><span class="line">   </span><br><span class="line">    <span class="function">Sales_item <span class="title">ret</span><span class="params">(lhs)</span></span>;</span><br><span class="line">    <span class="keyword">return</span></span><br><span class="line">    ret += rhs;</span><br><span class="line">    <span class="keyword">return</span> ret;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">Sales_item item1, item2, sum;</span><br><span class="line"><span class="keyword">while</span> (<span class="built_in">cin</span> &gt;&gt; item1 &gt;&gt; item2) &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        sum = item1 + item2;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (<span class="keyword">const</span> runtime_error &amp;e) &#123;</span><br><span class="line">        <span class="built_in">cerr</span> &lt;&lt; e.what() &lt;&lt; <span class="string">" Try again.\n"</span></span><br><span class="line">             &lt;&lt; endl;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h2 id="2-_Throwing_an_Exception_of_Class_Type">2. Throwing an Exception of Class Type</h2><p>An exception is raised by throwing an object. The type of that object determines which handler will be invoked. The selected handler is the one nearest in the call chain that matches the type of the object.</p>
<p>Exceptions are thrown and caught in ways that are similar to how arguments are passed to functions. An exception can be an object of any type that can be passed to a nonreference parameter, meaning that it must be possible to copy objects of that type. Recall that when we pass an argument of array or function type, that argument is automatically converted to an pointer. The same automatic conversion happens for objects that are thrown. As a consequence, there are no exceptions of array or function types. Instead, if we  throw an array, the thrown object is converted to a pointer to the first element in the array. Similarly, if we throw a function, the function is converted to a pointer to the function. The fact that control passes from one location to another has two important implications:</p>
<ul>
<li>Functions along the call chain are prematurely exited. Following section discusses what happens when functions are exited due to an exception.</li>
<li>In general, the storage that is local to a block that throws an exception is not around when the exception is handled.</li>
</ul>
<p>Because local storage is freed while handling an exception, the object that is thrown is not stored locally. Instead, the  throw expression is used to initialize a special object referred to as the exception object . The exception object is managed by the compiler and is guaranteed to reside in space that will be accessible to whatever  catch is invoked. This object is created by a<br>throw , and is initialized as a copy of the expression that is thrown. The exception object is passed to the corresponding  catch and is destroyed after the exception is completely handled. The exception object is created by copying the result of the thrown<br>expression; that result must be of a type that can be copied. What’s important to know is how the form of the throw expression interacts with types related by inheritance. When an exception is thrown, the static, compile-time type of the thrown object determines the type of the exception object.</p>
<p>The one case where it matters that a throw expression throws the static type is if we dereference a pointer in a throw. The result of dereferencing a pointer is an object whose type matches the type of the pointer. If the pointer points to a type from an inheritance hierarchy, it is possible that the type of the object to which the pointer points is different from the type of<br>the pointer. Regardless of the object’s actual type, the type of the exception object matches the static type of the pointer. If that pointer is a base-class type pointer that points to a derived-type object, then that object is sliced down; only the base-class part is thrown.</p>
<p>In particular, it is always an error to throw a pointer to a local object for the same reasons as it is an error to return a pointer to a local object from a function. It is usually a bad idea to  tHRow a pointer: Throwing a pointer requires that the object to which the pointer points exist wherever the corresponding handler resides.</p>
<h2 id="3-_Stack_Unwinding">3. Stack Unwinding</h2><p>When an exception is thrown, execution of the current function is suspended and the search begins for a matching  catch clause. The search starts by checking whether the  tHRow itself is located inside a try block. If so, the catch clauses associated with that try are examined to see if one of them matches the thrown object. If a matching  catch is found, the exception is<br>handled. If no catch is found, the current function is exitedits memory is freed and local objects are destroyed and the search continues in the calling function.</p>
<p>If the call to the function that threw is in a  try block, then the  catch clauses associated with that try are examined. If a matching  catch is found, the exception is handled. If no matching catch is found, the calling function is also exited, and the search continues in the function that called this one.</p>
<p>This process, known as stack unwinding, continues up the chain of nested function calls until a catch clause for the exception is found. As soon as a catch clause that can handle the exception is found, that  catch is entered, and execution continues within this handler. When the catch completes, execution continues at the point immediately after the last  catch clause associated with that try block.</p>
<p>When a function is exited due to an exception, the compiler guarantees that the local objects are properly destroyed. During stack unwinding, the memory used by local objects is freed and destructors for local objects of class type are run.</p>
<p>Destructors are often executed during stack unwinding. When destructors are executing, the exception has been raised but not yet handled. While stack unwinding is in progress for an exception, a destructor that throws another exception of its own that it does not also handle, causes the library  terminate function is called. Ordinarily,  terminate calls  abort , forcing an abnormal exit from the entire program. Because terminate ends the program, it is usually a very bad idea for a destructor to do anything that might cause an exception. The standard library types all guarantee that their destructors will not raise an exception.</p>
<p>Unlike destructors, it is often the case that something done inside a constructor might throw an exception. If an exception occurs while constructing an object, then the object might be only partially constructed. Some of its members might have been initialized, and others might not have been initialized before the exception occurs. Even if the object is only partially constructed, we are guaranteed that the constructed members will be properly destroyed. Similarly, an exception might occur when initializing the elements of an array or other container type. Again, we are guaranteed that the constructed elements will be destroyed.</p>
<p>uncaught exceptions terminate the program.</p>
<h2 id="3-_Catching_an_Exception">3. Catching an Exception</h2><p>The exception specifier in a catch clause looks like a parameter list that contains exactly one parameter. The exception specifier is a type name followed by an optional parameter name. During the search for a matching  catch , the catch that is found is not necessarily the one that matches the exception best. Instead, the  catch that is selected is the first  catch found that can<br>handle the exception. As a consequence, in a list of  catch clauses, the most specialized  catch must appear first. Most conversions are not allowed the types of the exception and the catch specifier must match exactly with only a few possible differences:</p>
<ul>
<li>Conversions from non const to  const are allowed. That is, a  throw of a non const object can match a catch specified to take a  const reference.</li>
<li>Conversions from derived type to base type are allowed.</li>
<li>An array is converted to a pointer to the type of the array; a function is converted to the appropriate pointer to function type.</li>
</ul>
<p>In particular, neither the standard arithmetic conversions nor conversions defined for class types are permitted.</p>
<p>When a catch is entered, the  catch parameter is initialized from the exception object. As with a function parameter, the exception-specifier type might be a reference. The exception object itself is a copy of the object that was thrown. Whether the exception object is copied again into the catch site depends on the exception-specifier type. Like a parameter declaration, an exception specifier for a base class can be used to  catch an exception object of a derived type. Usually, a catch clause that handles an exception of a type related by inheritance ought to define its parameter as a reference. Because objects (as opposed to references) are not polymorphic.</p>
<p>Because catch clauses are matched in the order in which they appear, programs that use exceptions from an inheritance hierarchy must order their  catch clauses so that handlers for a derived type occurs before a  catch for its base type.</p>
<h2 id="4-_Rethrow">4. Rethrow</h2><p>A catch can pass the exception out to another  catch further up the list of function calls by rethrowing the exception. A rethrow is a  throw that is not followed by a type or an expression: throw; An empty throw can appear only in a catch or in a function called (directly or indirectly) from a  catch. If an empty throw is encountered when a handler is not active,  terminate is called.</p>
<p>The exception that is thrown is the original exception object, not the catch parameter. When a  catch parameter is a base type, then we cannot know the actual type thrown by a rethrow expression. That type depends on the dynamic type of the exception object, not the static type of the catch parameter. In general, a  catch might change its parameter. If, after changing its parameter, the  catch rethrows the exception, then those changes will be propagated only if the exception specifier is a reference:<br><figure class="highlight actionscript"><table><tr><td class="code"><pre><span class="line"><span class="keyword">catch</span> (my_error &amp;eObj) &#123; <span class="comment">// specifier is a reference type</span></span><br><span class="line">    eObj.status = severeErr; <span class="comment">// modifies the exception object</span></span><br><span class="line">    <span class="keyword">throw</span>; <span class="comment">// the status member of the exception object is severeErr</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (other_error eObj) &#123; <span class="comment">// specifier is a nonreference type</span></span><br><span class="line">    eObj.status = badErr; <span class="comment">// modifies local copy only</span></span><br><span class="line">    <span class="keyword">throw</span>; <span class="comment">// the status member of the exception rethrown is unchanged</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h2 id="5-_The_Catch-All_Handler">5.  The Catch-All Handler</h2><p>A  catch(…) is often used in combination with a rethrow expression. The  catch does whatever local work can be done and then rethrows the exception:<br><figure class="highlight aspectj"><table><tr><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">manip</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        <span class="comment">// actions that cause an exception to be thrown</span></span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">        <span class="comment">// work to partially handle the exception</span></span><br><span class="line">        <span class="keyword">throw</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h2 id="6-_Function_Try_Blocks_and_Constructors">6. Function Try Blocks and Constructors</h2><p>Constructor initializers are processed before the constructor body is entered. A catch clause inside the constructor body cannot handle an exception that might occur while processing a constructor initializer. To handle an exception from a constructor initializer, we must write the constructor as a function try block.<br><figure class="highlight nimrod"><table><tr><td class="code"><pre><span class="line"><span class="keyword">template</span> &lt;class T&gt; <span class="type">Handle</span>&lt;T&gt;::<span class="type">Handle</span>(T *p)</span><br><span class="line"><span class="keyword">try</span> : <span class="keyword">ptr</span>(p), use(new size_t(<span class="number">1</span>))</span><br><span class="line">&#123;</span><br><span class="line">    // empty function body</span><br><span class="line">&#125; </span><br><span class="line">catch(<span class="keyword">const</span> std::bad_alloc &amp;e)</span><br><span class="line">&#123; </span><br><span class="line">    handle_out_of_memory(e);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>

      
    </div>
    <footer class="article-footer">
      <a data-url="https://zhouzijiang.github.io/2016/03/18/c-primer笔记17-exception/" data-id="cinvexixe0029tw3ag8824yyl" class="article-share-link">Share</a>
      
      
  <ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/c-基础/">c++基础</a></li></ul>

    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2016/03/18/c-primer笔记18-exception/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Newer</strong>
      <div class="article-nav-title">
        
          c++ primer笔记18: exception
        
      </div>
    </a>
  
  
    <a href="/2016/03/16/c-primer笔记16-pointer-to-function/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Older</strong>
      <div class="article-nav-title">c++ primer笔记16: pointer to function</div>
    </a>
  
</nav>

  
</article>

</section>
        
          <aside id="sidebar">
  
    
  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Tags</h3>
    <div class="widget">
      <ul class="tag-list"><li class="tag-list-item"><a class="tag-list-link" href="/tags/TCP/">TCP</a><span class="tag-list-count">5</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/c/">c++</a><span class="tag-list-count">2</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/c-基础/">c++基础</a><span class="tag-list-count">28</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/gdb/">gdb</a><span class="tag-list-count">1</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/linux/">linux</a><span class="tag-list-count">4</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/linux点滴/">linux点滴</a><span class="tag-list-count">3</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/svn/">svn</a><span class="tag-list-count">4</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/vim/">vim</a><span class="tag-list-count">1</span></li></ul>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Tag Cloud</h3>
    <div class="widget tagcloud">
      <a href="/tags/TCP/" style="font-size: 18px;">TCP</a> <a href="/tags/c/" style="font-size: 12px;">c++</a> <a href="/tags/c-基础/" style="font-size: 20px;">c++基础</a> <a href="/tags/gdb/" style="font-size: 10px;">gdb</a> <a href="/tags/linux/" style="font-size: 16px;">linux</a> <a href="/tags/linux点滴/" style="font-size: 14px;">linux点滴</a> <a href="/tags/svn/" style="font-size: 16px;">svn</a> <a href="/tags/vim/" style="font-size: 10px;">vim</a>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Archives</h3>
    <div class="widget">
      <ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/archives/2016/04/">四月 2016</a><span class="archive-list-count">1</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2016/03/">三月 2016</a><span class="archive-list-count">27</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2016/02/">二月 2016</a><span class="archive-list-count">10</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2016/01/">一月 2016</a><span class="archive-list-count">4</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2015/12/">十二月 2015</a><span class="archive-list-count">7</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2015/11/">十一月 2015</a><span class="archive-list-count">5</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2015/08/">八月 2015</a><span class="archive-list-count">1</span></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2015/07/">七月 2015</a><span class="archive-list-count">2</span></li></ul>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Recents</h3>
    <div class="widget">
      <ul>
        
          <li>
            <a href="/2016/04/23/gdb-1-启动和退出/">gdb(1):启动和退出</a>
          </li>
        
          <li>
            <a href="/2016/03/29/最让人头疼的歧义most-vexing-parse/">最让人头疼的歧义most vexing parse</a>
          </li>
        
          <li>
            <a href="/2016/03/29/不可复制noncopyable/">不可复制noncopyable</a>
          </li>
        
          <li>
            <a href="/2016/03/26/线程同步之条件变量/">线程同步之条件变量</a>
          </li>
        
          <li>
            <a href="/2016/03/21/c-primer笔记27-Pointer-to-Class-Member/">c++ primer笔记27: Pointer to Class Member</a>
          </li>
        
      </ul>
    </div>
  </div>

  
</aside>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2016 zhouzijiang<br>
      Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>
    </div>
  </div>
</footer>
    </div>
    <nav id="mobile-nav">
  
    <a href="/" class="mobile-nav-link">Home</a>
  
    <a href="/archives" class="mobile-nav-link">Archives</a>
  
</nav>
    

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


  <link rel="stylesheet" href="/fancybox/jquery.fancybox.css" type="text/css">
  <script src="/fancybox/jquery.fancybox.pack.js" type="text/javascript"></script>


<script src="/js/script.js" type="text/javascript"></script>

  </div>
</body>
</html>